### ISSUE TITLE
Admob Native Crashes

### ISSUE THREAD

**Issue by Amaeta** [EYALIN/community-admob-plus#4]
This community-admob-plus sorted my issues with admob. My concern now is with the native admob.
I have sorted out the admob native. It displays but sometimes it crashes my app (guess when it is not loaded). My code is
if(ad.showfail || ad.loadfail){
//ad.show();
}else{
new Promise(function(resolve){
setTimeout(function() {
ad.hide();
resolve();

	}, 12000);
	});
	ad.showWith(document.getElementById('nativeads'));
	ad.load();
	}
How can I catch the error? Please help!

**Comment by EYALIN** [comment]
personally, I'm not using the native ads, it is killing the UI.
native ads are not supported in web apps. 
you can try the web view ads https://github.com/admob-plus/admob-plus/pull/539, there are guides there on how to do it.

anyway, i'm closing this issue, because there is no way to solve it. no matter how you will implement it, it will pass ADMOB review.
